apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  namespace: roboshop
  annotations:
    project: roboshop
    env: dev
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx