apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    purpose: headless-service
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      purpose: headless-service
      project: roboshop
  template:
    metadata:
      labels:
        purpose: headless-service
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: headless-service
    project: roboshop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-headless
# spec:
#   ClusterIp: None
#   selector:
#     purpose: headless-service
#     project: roboshop
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 80